name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: Check for build and type issues
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun index.ts
      - run: bun run build

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: bun install

        # use astro check for issues
      - name: Run check
        run: bun astro check

        # ensure build works
      - name: Run build
        run: bun build
